# От этой строчки НЕЛЬЗЯ менять параметры
defaults:
  - _self_
  - override hydra/hydra_logging: default
  - override hydra/job_logging: default

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .

# От этой строчки МОЖНО менять параметры
PATH_TO_DOWNLOAD_FROM_INTERNET:
  url: "https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv" # URL на скачивание датасета
  output_dir: "././data/raw" # Не трогать, т.к. отправляет файл в папку data/raw
  filename: "iris.csv" # Имя сохраняемого файла (датасета) 

PATH_DVC_TO_GDRIVE:
  name: "gdrive" # Имя удалённого хранилища DVC 
  remote_name: "myremote" # Имя удалённого хранилища DVC (Если меняете, не забедьте удалить старое хранилище)
  gdrive_folder_id: "1Le1Dyp051-zlFaSeRtRF67bAFkkPan_e" # ID папки в Google Drive
  repo_path: "././data/raw" # Путь к папке, где находится датасет (Желательно не трогать)
  repo_name: "iris.csv" # Имя сохраняемого файла (датасета)
